templates/function/package.json.mustache
templates/swagger/package.json.mustache

I added default keyword, "node-red-nodegen" into package.json templates. It will be useful for Node-RED users to search nodes created by node generator.

Add default keyword into package.json templates

---

.github/PULL_REQUEST_TEMPLATE.md
.gitignore
.travis.yml
Gruntfile.js
package.json

I added test method using mocha same as Node-RED core project.
This function will be useful to keep quality of the code.

 Add test method using mocha

---

lib/nodegen.js
test/lib/nodegen_spec.js

To fix #6, I used synchronous functions instead of asynchronous functions.
And this supports multiple icon files under icons directory.

Fix asynchronous bug

---

.gitignore
.travis.yml
package.json
test/nodegen/helper.js
test/nodegen/node-red-contrib-lowercase/node_spec.js
test/nodegen/node-red-contrib-swagger-petstore/node_spec.js

I added test cases for the following nodes created by node-red-nodegen command.
- function node (created from JavaScript code in sample/lower-case.js)
- swagger node (created from swagger definition in http://petstore.swagger.io/v2/swagger.json)

Add test cases for generated nodes

---

test/nodegen/node-red-contrib-swagger-petstore/node_spec.js

Current test case for swagger node fails because there isn't the key, "123" in the data from swagger petstore server.
I changed "123" to "available" which the server returns as default key.

Fix Travis error

---

.travis.yml

Currently test cases for petstore use http://petstore.swagger.io .
I changed it to use petstore on docker on travis. 
and I removed node.js v7 from travis because node.js v7 is not LTS.

Use petstore on docker instead of petstore.swagger.io

---

.gitignore
.travis.yml
Gruntfile.js
package.json

I moved node generating procedures from travis settings to Gruntfile.js because  developers needed to generate test nodes manually in local environment.

Generate nodes in grunt command

---

bin/node-red-nodegen.js
lib/nodegen.js
package.json
templates/function/node.html.mustache
templates/function/package.json.mustache
templates/swagger/node.html.mustache
templates/swagger/package.json.mustache
test/lib/nodegen_spec.js

fix swagger templates to correctly handle code generation in case of token authorization
I added two new configuration options, to increase the flexibility of code generation:
'--keywords' option in command line to set additional keywords on the generated node along the default, 'node-red-node gen'
'--category' option in command line to configure node category instead of the default, 'function'

--keywords and --category options

---

templates/swagger/node.js.mustache
test/nodegen/node-red-contrib-swagger-petstore/node_spec.js

The node generated by Swagger template throws an error when the node refers to the undefined variables. To fix the problem, I added conditions to check the values.

Fix undefined variable bug

---

lib/nodegen.js

remove special chars in swagger 'operationId', because this property is used in code generation tools for method names, and it can lead to invalid code

sanitize operationId in swagger definition

---

lib/nodegen.js
templates/swagger/locales/en-US/node.json.mustache
templates/swagger/node.html.mustache
templates/swagger/node.js.mustache
templates/swagger/package.json.mustache

This change enables to externaly override node properties (i.e. on the incoming msg).
It also allows for mustache templating on the node property (i.e. use {{attribute}} in the node UI to explicitly reference a msg attribute).
I also cleaned up the code generation template in case of 'body' parameter, to reduce code clutter and make the generated code a bit more intuitive for human reading.

enable override of node properties and clean up codegen template 

---

templates/swagger/node.html.mustache

I fixed #23.
I added conditions to exclude typedInput pulldown menu when swagger definition has enum in parameter.

Fix typedInput bug

---

lib/nodegen.js

node-red-nodegen command shows the following error message when user inputs both module name and prefix.
"Error: error: module name and prefix are conflicted."
Because the message contains "error" two times, I deleted the second one.

Remove duplicated error message

---

Gruntfile.js
bin/getswagger.js

Travis CI always fails because swagger definition and docker image was changed in petstore test server. The latest swagger definition uses HTTPS protocol but the docker image doesn't support the protocol. To use HTTP protocol in the test case, I added program to get swagger definition and remove HTTPS.

Fix bug in travis CI

---

.gitignore

In the current .gitignore setting, developers cannot add test case files under "/test/nodegen" directory because the setting ignore both "/nodegen" and "/test/nodegen" directories.
Therefore, I added slash character, "/" to ignore only "/nodegen" directory which has generated nodes.

Fix problem when add test cases under test/nodegen directory

---

bin/node-red-nodegen.js
package.json

I added version check option for node generator command line.
It will be useful to report version when users report some problem about node generator.

Add version check option

---

test/lib/nodegen_spec.js

Test case for node generator library doesn't remove all files in generated node after the node is tested.
Therefore, I modified the deleting handling.

Fix delete bug for library test cases

---

templates/function/package.json.mustache
templates/swagger/package.json.mustache

Current node generator generates package.json file which has four spaces as indent. npm init command generates package.json file whose indent size is two spaces. Therefore, all lines will be changed when npm init command modifies package.json file generated from node generator. To solve the problem, I changed indent size in package.json templates.

Modify indent size in package.json

---

lib/nodegen.js
templates/swagger/node.html.mustache
templates/swagger/node.js.mustache
templates/swagger/test/node_spec.js.mustache
test/nodegen/node-red-contrib-swagger-petstore/node_spec.js

When swagger definition doesn't have host name and security setting, generated node has unnecessary configuration node (users need to input only name of configuration node). To solve the problem, I added handling to remove configuration node in the case.

Fix unnecessary configuration node

---

templates/swagger/node.js.mustache

Current node which is generated from swagger definition cannot catch error because node.error() has only first argument. To solve the problem, I added msg variable as the second argument.

Fix node.error() handling

---

bin/getswagger.js
bin/node-red-nodegen.js
lib/nodegen.js
package.json
templates/function/node.html.mustache
templates/swagger/node.html.mustache

To support --color and --icon options for command line, I added the source code.
Using these options, node developers can directly specify node color and icon without modifying node's html files manually.

Support node color and icon options

---

templates/swagger/node.js.mustache

When the node generated from swagger encounters an error (ex. HTTP 404), it throws the error and a catch node can catch the error in the current implementation. But the error event does not contain the details of the error. Therefore, it is difficult for the flow after catch node to handle the error. To solve this problem, I added information (same as http request node) for error handling into swagger node template.

 Add information for error handling into swagger node template

---

lib/nodegen.js

`swagger.security` is a definition for the whole API. It is not necessarily set when there is security on individual methods.
Therefore it is better to refer to `swagger.securityDefinitions` to see if you need ` hasServiceParams`.
`isSecure` judgment also refers to ` swagger.securityDefinitions`.
Ref: https://github.com/wcandillon/swagger-js-codegen/blob/master/lib/codegen.js#L41

Fixed the condition of `hasServiceParams`

---

docs/index.md

Fix English Docs to sound more natural...for the most part.

proofread docs/index

---

README.md

Updated the README.md to expand on the 'Example 2' description of how to save the function node

Updated 'Example 2' save function section

---

lib/nodegen.js
templates/function/examples/flow.json.mustache

I added functionality to create a sample flow for the function node template.

Add example flow to function node template

---

lib/webofthings/index.js
lib/webofthings/wotutils.js
templates/webofthings/node.js.mustache
templates/webofthings/package.json.mustache

- Update CoAP support in Web of Things node generation.
- Update version of dependent npm modules.

improve CoAP and IPv6 support

---

README.md
package.json
templates/function/package.json.mustache
templates/subflow/package.json.mustache
templates/subflow/subflow.js.mustache
templates/swagger/package.json.mustache
templates/webofthings/package.json.mustache

I updated the dependency modules in package.json files.

Update dependency modules

---

templates/webofthings/node.js.mustache
templates/webofthings/package.json.mustache

- Switched back package `url-template` to v2.0.8 in WoT TD template because our code does not support ESM yet.
- Fix schema validation logic of values for URI template.

fix uri-schema handling in WoT TD

---

README.md
lib/subflow/index.js
package.json
samples/qrcode.json
templates/subflow/README.md.mustache
templates/subflow/package.json.mustache
templates/subflow/subflow.js.mustache

I found that the generated README.md file doesn't contain the subflow node information in exporting subflow functionality. Therefore, I fixed it in this pull request.

Output subflow information to README.md

---

bin/node-red-nodegen.js
lib/subflow/index.js

When the subflow definition has no module properties, the current implementation mistakenly detects this definition as a function node like in https://github.com/node-red/node-red-nodegen/issues/133. To navigate the module property UI of the subflow, I added this handling to show the reason for the error.

Add error handling for no module property in subflow
