templates/swagger/node.html.mustache
=> Fix typo at placeholder

templates/swagger/node.html.mustache, templates/swagger/node.js.mustache
fix swagger templates to correctly handle code generation in case of token authorization
=> fix swagger templates (try #2)

templates/swagger/locales/zh-CN/node.json.mustache
=> Translated node.json.mustache to Chinese

templates/swagger/locales/en-US/node.json.mustache, templates/swagger/locales/ja/node.json.mustache, templates/swagger/locales/zh-CN/node.json.mustache, templates/swagger/node.html.mustache
I fixed #25.
To refer to language files, I modified method names in Swagger node.
=> Support i18n in method name

lib/nodegen.js
I fixed #27 
Use `path.join()` to make file path instead of `str + str + ...`
=> Use path.join() to make filepath

lib/nodegen.js
PR for the issue #28  
Including extention string in path.join method.
=> Fix to include .tgz in path.join

bin/node-red-nodegen.js, lib/nodegen.js, package.json, test/lib/nodegen_spec.js
I fixed #32.
I added appropriate error handling for node generator.
=> Add error handling

.travis.yml
As Node.js version4 is no longer supported, removed it.
Added version 10 and `matrix include` description.
The above fix is following this pull request.
https://github.com/node-red/node-red/pull/1708
=> Removed Node.js v4, added Node.js v10

package.json
I updated javascript-obfuscator module from 0.12.2 to 0.16.0 .
=> Fix module version update

Gruntfile.js, samples/handle-clearInterval.js, samples/handle-setInterval.js, samples/handle-setTimeout.js, samples/log-a-Warning-Message.js, samples/log-an-Error-Message.js, samples/log-an-Info-Message.js, test/nodegen/node-red-contrib-handle-clear-interval/node_spec.js, test/nodegen/node-red-contrib-handle-set-interval/node_spec.js, test/nodegen/node-red-contrib-handle-set-timeout/node_spec.js, test/nodegen/node-red-contrib-log-a-warning-message/node_spec.js, test/nodegen/node-red-contrib-log-an-error-message/node_spec.js, test/nodegen/node-red-contrib-log-an-info-message/node_spec.js
To improve code coverage, I added test cases for function node template.
=> Add test cases for function node template

test/nodegen/node-red-contrib-handle-clear-interval/node_spec.js, test/nodegen/node-red-contrib-handle-set-interval/node_spec.js, test/nodegen/node-red-contrib-handle-set-timeout/node_spec.js, test/nodegen/node-red-contrib-log-a-warning-message/node_spec.js, test/nodegen/node-red-contrib-log-an-error-message/node_spec.js, test/nodegen/node-red-contrib-log-an-info-message/node_spec.js, test/nodegen/node-red-contrib-lowercase/node_spec.js, test/nodegen/node-red-contrib-swagger-petstore/node_spec.js
I fixed #38.
I added helper.stopServer() in after() section of test cases.
=> Add helper.stopServer() in test cases

lib/nodegen.js
I fixed #41.
I added error handling to avoid invalid node name.
=> Add error handling to check invalid node name

Gruntfile.js
I fixed #44 .
I separated node generator commands to tasks in Gruntfile.js
=> Support Windows to run grunt

lib/nodegen.js, templates/function/package.json.mustache, templates/function/test/node_spec.js.mustache
I added test script file into function node template.
The test script file is essential for generated nodes to maintain quality of code.
=> Add test method into function node template

test/nodegen/node-red-contrib-swagger-petstore/node_spec.js
I add test cases for swagger petstore node.
=> Add test cases for swagger petstore node

lib/nodegen.js, templates/swagger/package.json.mustache, templates/swagger/test/node_spec.js.mustache
I added test method into swagger node template.
=> Add test method into swagger node template

templates/swagger/node.html.mustache, templates/swagger/node.js.mustache
I removed unnecessary lines and added necessary lines in swagger node template.
=> Remove and add lines in swagger node template

Gruntfile.js, samples/get-keys-in-flow-context.js, test/nodegen/node-red-contrib-get-keys-in-flow-context/node_spec.js
I added test case for function node template.
=>  Add test case for function node template (get keys in flow context)

Gruntfile.js, samples/get-node-context.js, test/nodegen/node-red-contrib-get-node-context/node_spec.js
added test case for get node context
=> Added new test case

Gruntfile.js, samples/set-global-context.js, test/nodegen/node-red-contrib-set-global-context/node_spec.js
I added a test case for function node template
=> Add a test case of set global context

Gruntfile.js, samples/set-flow-context.js, test/nodegen/node-red-contrib-set-flow-context/node_spec.js
I added a test case for function node template.
=> Add a test case for function node template (set flow context)

Gruntfile.js, samples/get-flow-context1.js, samples/get-flow-context2.js, test/nodegen/node-red-contrib-get-flow-context1/node_spec.js, test/nodegen/node-red-contrib-get-flow-context2/node_spec.js
I add test cases for function node template (get flow context).
=> Add test cases for function node template (get flow context)

Gruntfile.js, samples/get-global-context1.js, samples/get-global-context2.js, test/nodegen/node-red-contrib-get-global-context1/node_spec.js, test/nodegen/node-red-contrib-get-global-context2/node_spec.js
I added test cases for function node template.
=> Add test cases for function node template (get global context1,2)

Gruntfile.js, samples/set-node-context.js, test/nodegen/node-red-contrib-set-node-context/node_spec.js
Add a test case for function node template (set node context)
=> Add a test case for function node template (set node context)

Gruntfile.js, samples/send-returned-message.js, test/nodegen/node-red-contrib-send-returned-message/node_spec.js
I added a test case for function node template (send returned message).
=> Add a test case for function node template (send returned message)

Gruntfile.js, samples/send-returned-message-using-send.js, test/nodegen/node-red-contrib-send-returned-message-using-send/node_spec.js
I added a test case for function node template (send returned message using send() ).
=> Add a test case for function node template

templates/function/node.html.mustache
I removed unnecessary information and code in function node template. And I added node information template.
=> Update function node template

templates/function/test/node_spec.js.mustache
I added before() and after() methods which are required in test cases.
=> Add before() and after() in test case template

Gruntfile.js
I updated timeout options for grunt test.
=> Update timeout values for grunt test

README.md
I added description of the tool and command line options.
And I changed installation method from git to npmjs.
=> Add description and options in README.md

test/lib/nodegen_spec.js
I improved test case of node generator library to cover more code.
=> Improve test case of library

Gruntfile.js, samples/get-keys-in-node-context.js, test/nodegen/node-red-contrib-get-keys-in-node-context/node_spec.js
I added a test case for function node template (get keys in flow context).
=> Add test case for function node template (get keys in flow context)

package.json
I fixed #65.
To solve the grunt coverage problem, I added istanbul module into devDependencies in package.json.
=> Add istanbul module into devDependencies

package.json
I added contributor's names into package.json.
=> Add contributors into package.json

Gruntfile.js, samples/pass-through-topic.js, test/nodegen/node-red-contrib-pass-through-topic/node_spec.js
I added test case for function node template (pass through topic).
=> Add test case for function node template

bin/node-red-nodegen.js
I found that usage message lacks ']' in command line. Therefore, I added the character in the code.
=> Fix typo in usage message

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
I updated GitHub template files to be same as Node-RED core project.
It will become easy for core developers to understand the formats.
=> Update templates for issue and pull request

.travis.yml, Gruntfile.js, package.json
=> modified Travis' definition as in node-red project

templates/swagger/locales/de-DE/node.json.mustache
=> german translation for node generator swagger node template

package.json
I added new contributor (#72) into package.json.
=> Add contributor into package.json

bin/node-red-nodegen.js, package.json
I added code to support OpenAPI 3.0 as one of the source input data.
=> Support OpenAPI 3.0 as source data

lib/util.js, templates/function/.travis.yml.mustache, templates/swagger/.travis.yml.mustache, templates/webofthings/.travis.yml.mustache, test/lib/function_spec.js, test/lib/swagger_spec.js
I also removed files related to Travis CI from the node templates.
=> Remove Travis CI files from node templates

lib/subflow/index.js, lib/swagger/index.js, templates/function/package.json.mustache, templates/subflow/README.md.mustache, templates/subflow/package.json.mustache, templates/swagger/package.json.mustache, templates/webofthings/package.json.mustache
I updated the node templates to be suitable for `node-red-dev` and `npm init` commands.
=> Improve node templates

lib/webofthings/index.js, lib/webofthings/td-json-schema-validation.json, lib/webofthings/wotutils.js, package.json, templates/webofthings/node.js.mustache, templates/webofthings/package.json.mustache
- Initial MQTT binding support for Web of Things Thing Description
- Fix URI template handling
=> Add MQTT binding support for WoT Thing Description
